# Setup
title: 'Algoritmisk fagterminologi'
url: https://thorehusfeldt.github.io/algoritmisk-fagterminologi/

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York
analytics:
  tracking_id: UA-53167467-11

collections:
  words:
    output: true

defaults:
  - scope:
      path: ""
      type: "words"
    values:
      layout: word

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
